#!/bin/bash
# System Prompt Hook: phase_permission_guard
# Auto-generated by Claude Enhancer 5.0 Auto-Trigger System

PROJECT_ROOT="/home/xx/dev/Claude Enhancer 5.0"

# Phase Permission Guard
# Ensures Claude Code respects current workflow phase

CURRENT_PHASE=$(cat "$PROJECT_ROOT/.phase/current" 2>/dev/null || echo "0")
PHASE_NAME=$(case $CURRENT_PHASE in
    0) echo "Branch Creation" ;;
    1) echo "Requirements Analysis" ;;
    2) echo "Design Planning" ;;
    3) echo "Implementation" ;;
    4) echo "Local Testing" ;;
    5) echo "Code Commit" ;;
    6) echo "Code Review" ;;
    7) echo "Merge & Deploy" ;;
esac)

echo "🎯 Current Workflow Phase: $CURRENT_PHASE ($PHASE_NAME)"
echo "📋 Recommended actions for this phase:"

case $CURRENT_PHASE in
    0) echo "  - Create feature branch" ;;
    1) echo "  - Analyze requirements and user needs" ;;
    2) echo "  - Design architecture and plan implementation" ;;
    3) echo "  - Use 4-6-8 Agent strategy for parallel implementation" ;;
    4) echo "  - Run tests and validate functionality" ;;
    5) echo "  - Commit code with proper cleanup" ;;
    6) echo "  - Create PR and conduct code review" ;;
    7) echo "  - Deploy and perform final cleanup" ;;
esac

