#!/bin/bash
# System Prompt Hook: quality_gate_enforcer
# Auto-generated by Claude Enhancer 5.0 Auto-Trigger System

PROJECT_ROOT="/home/xx/dev/Claude Enhancer 5.0"

# Quality Gate Enforcer
# Enforces quality standards at key phases

case $CURRENT_PHASE in
    4) echo "🧪 Phase 4: Testing Required - Validate all functionality" ;;
    5) echo "🧹 Phase 5: Cleanup Required - Auto-cleanup will trigger" ;;
    6) echo "👥 Phase 6: Code Review Required - Create PR for team review" ;;
    7) echo "🚀 Phase 7: Deployment Ready - Final cleanup and deploy" ;;
esac

echo ""
echo "Quality Standards:"
echo "  ✅ All code must be tested"
echo "  ✅ No temporary files in commits"
echo "  ✅ Follow naming conventions"
echo "  ✅ Security scan passed"

