#!/bin/bash
# Auto-mode detection
if [[ "$CE_AUTO_MODE" == "true" ]]; then
    export CE_SILENT_MODE=true
fi
# System Prompt Hook: workflow_compliance_check
# Auto-generated by Claude Enhancer 5.0 Auto-Trigger System

PROJECT_ROOT="/home/xx/dev/Claude Enhancer 5.0"

# Workflow Compliance Check
# Reminds Claude Code to follow 8-Phase workflow

echo "📚 Claude Enhancer 5.0 Workflow Reminder:"
echo "  Phase 0-7: Complete lifecycle from branch to deployment"
echo "  4-6-8 Strategy: Select appropriate Agent count based on complexity"
echo "  Quality Gates: Built-in hooks ensure code quality at each phase"
echo ""
echo "⚠️  Remember: Only Claude Code can orchestrate SubAgents"
echo "🎯 Focus: Complete the current phase before advancing"

