# Prometheus配置文件
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'perfect21-cluster'
    environment: 'production'

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Perfect21 API监控
  - job_name: 'perfect21-api'
    static_configs:
      - targets: ['perfect21-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # PostgreSQL监控
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis监控
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # 系统监控
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Nginx监控
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Docker容器监控
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Git工作流监控
  - job_name: 'git-workflow'
    static_configs:
      - targets: ['perfect21-api:8000']
    metrics_path: '/metrics/git'
    scrape_interval: 60s

  # Agent执行监控
  - job_name: 'agent-execution'
    static_configs:
      - targets: ['perfect21-api:8000']
    metrics_path: '/metrics/agents'
    scrape_interval: 30s

  # 自监控
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']