# =============================================================================
# Prometheus Configuration for Perfect21 Claude Enhancer
# Comprehensive monitoring and alerting setup
# =============================================================================

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'claude-enhancer-production'
    region: 'us-west-2'

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Rules files
rule_files:
- "alert_rules.yml"

# Scrape configurations
scrape_configs:
# Prometheus itself
- job_name: 'prometheus'
  static_configs:
  - targets: ['localhost:9090']
  scrape_interval: 30s
  metrics_path: /metrics

# Claude Enhancer Application
- job_name: 'claude-enhancer'
  kubernetes_sd_configs:
  - role: pod
    namespaces:
      names:
      - claude-enhancer
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name
  scrape_interval: 15s
  metrics_path: /metrics

# PostgreSQL Database
- job_name: 'postgres'
  kubernetes_sd_configs:
  - role: service
    namespaces:
      names:
      - claude-enhancer
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name]
    action: keep
    regex: postgres-exporter-service
  - source_labels: [__meta_kubernetes_service_port_name]
    action: keep
    regex: metrics
  scrape_interval: 30s

# Redis Cache
- job_name: 'redis'
  kubernetes_sd_configs:
  - role: service
    namespaces:
      names:
      - claude-enhancer
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name]
    action: keep
    regex: redis-exporter-service
  - source_labels: [__meta_kubernetes_service_port_name]
    action: keep
    regex: metrics
  scrape_interval: 30s

# Nginx Load Balancer
- job_name: 'nginx'
  kubernetes_sd_configs:
  - role: service
    namespaces:
      names:
      - claude-enhancer
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_name]
    action: keep
    regex: nginx-exporter-service
  - source_labels: [__meta_kubernetes_service_port_name]
    action: keep
    regex: metrics
  scrape_interval: 30s

# Kubernetes API Server
- job_name: 'kubernetes-apiservers'
  kubernetes_sd_configs:
  - role: endpoints
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabel_configs:
  - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
    action: keep
    regex: default;kubernetes;https

# Kubernetes Nodes
- job_name: 'kubernetes-nodes'
  kubernetes_sd_configs:
  - role: node
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: kubernetes.default.svc:443
  - source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics

# Kubernetes Pods
- job_name: 'kubernetes-pods'
  kubernetes_sd_configs:
  - role: pod
  relabel_configs:
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
    action: replace
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
    target_label: __address__
  - action: labelmap
    regex: __meta_kubernetes_pod_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_pod_name]
    action: replace
    target_label: kubernetes_pod_name

# Kubernetes Services
- job_name: 'kubernetes-services'
  kubernetes_sd_configs:
  - role: service
  relabel_configs:
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
    action: keep
    regex: true
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scheme]
    action: replace
    target_label: __scheme__
    regex: (https?)
  - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_path]
    action: replace
    target_label: __metrics_path__
    regex: (.+)
  - source_labels: [__address__, __meta_kubernetes_service_annotation_prometheus_io_port]
    action: replace
    target_label: __address__
    regex: ([^:]+)(?::\d+)?;(\d+)
    replacement: $1:$2
  - action: labelmap
    regex: __meta_kubernetes_service_label_(.+)
  - source_labels: [__meta_kubernetes_namespace]
    action: replace
    target_label: kubernetes_namespace
  - source_labels: [__meta_kubernetes_service_name]
    action: replace
    target_label: kubernetes_name

# Node Exporter for system metrics
- job_name: 'node-exporter'
  kubernetes_sd_configs:
  - role: endpoints
  relabel_configs:
  - source_labels: [__meta_kubernetes_endpoints_name]
    action: keep
    regex: node-exporter
  - source_labels: [__meta_kubernetes_endpoint_port_name]
    action: keep
    regex: metrics

# cAdvisor for container metrics
- job_name: 'kubernetes-cadvisor'
  kubernetes_sd_configs:
  - role: node
  scheme: https
  tls_config:
    ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  relabel_configs:
  - action: labelmap
    regex: __meta_kubernetes_node_label_(.+)
  - target_label: __address__
    replacement: kubernetes.default.svc:443
  - source_labels: [__meta_kubernetes_node_name]
    regex: (.+)
    target_label: __metrics_path__
    replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor

# Blackbox exporter for endpoint monitoring
- job_name: 'blackbox'
  metrics_path: /probe
  params:
    module: [http_2xx]
  static_configs:
  - targets:
    - https://claude-enhancer.com
    - https://api.claude-enhancer.com/health
    - https://auth.claude-enhancer.com/health
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: blackbox-exporter:9115

# External services monitoring
- job_name: 'external-services'
  static_configs:
  - targets:
    - 'external-api:8080'
    - 'payment-gateway:443'
  scrape_interval: 60s
  metrics_path: /metrics