apiVersion: v1
kind: ConfigMap
metadata:
  name: perfect21-config
  namespace: perfect21
data:
  production.yaml: |
    server:
      host: "0.0.0.0"
      port: 8000
      workers: 4
      max_connections: 1000
      keepalive_timeout: 65

    database:
      type: "postgresql"
      host: "postgres-service"
      port: 5432
      name: "perfect21"
      user: "perfect21_user"
      pool_size: 10
      max_overflow: 20
      pool_timeout: 30

    cache:
      type: "redis"
      default_ttl: 3600
      redis_host: "redis-service"
      redis_port: 6379
      redis_db: 0

    auth:
      access_token_expire_hours: 1
      refresh_token_expire_days: 7
      password_min_length: 8
      max_login_attempts: 5
      lockout_duration_minutes: 15

    rate_limiting:
      enabled: true
      default_max_requests: 1000
      default_window_seconds: 3600
      endpoint_limits:
        "/api/auth/login":
          max_requests: 10
          window_seconds: 600
        "/api/auth/register":
          max_requests: 5
          window_seconds: 3600

    logging:
      level: "INFO"
      file: "/var/log/perfect21/api.log"
      max_size: "50MB"
      backup_count: 10
      format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    perfect21:
      version: "2.3.0"
      mode: "production"
      data_dir: "/var/lib/perfect21/data"
      logs_dir: "/var/log/perfect21"
      temp_dir: "/tmp/perfect21"

    git_workflow:
      enabled: true
      auto_hooks: true
      branch_protection: true
      require_pr_review: true

    security:
      allowed_origins:
        - "https://perfect21.example.com"
        - "https://api.perfect21.example.com"
      cors_credentials: true
      secure_cookies: true
      session_secure: true
      content_type_nosniff: true
      frame_deny: true
      xss_protection: true

    monitoring:
      enabled: true
      metrics_endpoint: "/metrics"
      health_check_endpoint: "/health"
      performance_tracking: true

    task_execution:
      max_parallel_tasks: 5
      default_timeout: 300
      max_timeout: 1800
      result_cache_ttl: 3600

    backup:
      enabled: true
      schedule: "0 2 * * *"
      retention_days: 30
      backup_dir: "/var/lib/perfect21/backups"