# =============================================================================
# Kubernetes Secrets for Perfect21 Claude Enhancer
# Contains sensitive configuration data
# NOTE: Replace base64 encoded values with your actual secrets
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: claude-enhancer-secrets
  namespace: claude-enhancer
  labels:
    app.kubernetes.io/name: claude-enhancer
    app.kubernetes.io/component: configuration
type: Opaque
data:
  # Application secrets (base64 encoded)
  SECRET_KEY: eW91ci1zdXBlci1zZWNyZXQtYXBwbGljYXRpb24ta2V5LWNoYW5nZS10aGlzLWluLXByb2R1Y3Rpb24=

  # Database credentials
  DB_PASSWORD: eW91ci1zdXBlci1zZWN1cmUtZGF0YWJhc2UtcGFzc3dvcmQtaGVyZQ==
  DATABASE_URL: cG9zdGdyZXNxbCthc3luY3BnOi8vY2xhdWRlX3VzZXI6eW91ci1zdXBlci1zZWN1cmUtZGF0YWJhc2UtcGFzc3dvcmQtaGVyZUBwb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvY2xhdWRlX2VuaGFuY2Vy

  # Redis credentials
  REDIS_PASSWORD: eW91ci1yZWRpcy1zZWN1cmUtcGFzc3dvcmQtaGVyZQ==
  REDIS_URL: cmVkaXM6Ly86eW91ci1yZWRpcy1zZWN1cmUtcGFzc3dvcmQtaGVyZUByZWRpcy1zZXJ2aWNlOjYzNzkvMA==

  # JWT secrets
  JWT_ACCESS_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWFjY2Vzcy1rZXktbWluaW11bS0yNTYtYml0cy1sb25nLXJhbmRvbS1zdHJpbmc=
  JWT_REFRESH_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LXJlZnJlc2gta2V5LW1pbmltdW0tMjU2LWJpdHMtbG9uZy1kaWZmZXJlbnQtc3RyaW5n

  # External API keys
  OPENAI_API_KEY: eW91ci1vcGVuYWktYXBpLWtleQ==
  ANTHROPIC_API_KEY: eW91ci1hbnRocm9waWMtYXBpLWtleQ==

  # Monitoring secrets
  SENTRY_DSN: eW91ci1zZW50cnktZHNuLXVybA==
  DATADOG_API_KEY: eW91ci1kYXRhZG9nLWFwaS1rZXk=

  # Email configuration
  SMTP_PASSWORD: eW91ci1hcHAtcGFzc3dvcmQ=

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: claude-enhancer
  labels:
    app.kubernetes.io/name: postgres
    app.kubernetes.io/component: database
type: Opaque
data:
  POSTGRES_PASSWORD: eW91ci1zdXBlci1zZWN1cmUtZGF0YWJhc2UtcGFzc3dvcmQtaGVyZQ==
  POSTGRES_USER: Y2xhdWRlX3VzZXI=
  POSTGRES_DB: Y2xhdWRlX2VuaGFuY2Vy

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: claude-enhancer
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: cache
type: Opaque
data:
  REDIS_PASSWORD: eW91ci1yZWRpcy1zZWN1cmUtcGFzc3dvcmQtaGVyZQ==

---
# TLS Certificate Secret (replace with your actual certificates)
apiVersion: v1
kind: Secret
metadata:
  name: claude-enhancer-tls
  namespace: claude-enhancer
  labels:
    app.kubernetes.io/name: claude-enhancer
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Replace these with your actual base64-encoded certificate and key
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgoKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgoKLS0tLS1FTkQgUFJJVkFURSBLRVktLS0tLQo=