apiVersion: v1
kind: Secret
metadata:
  name: perfect21-secrets
  namespace: perfect21
  labels:
    app.kubernetes.io/name: perfect21
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Base64 encoded secrets - Replace with actual values
  jwt-secret-key: Y2hhbmdlLW1lLXRvLWEtcmFuZG9tLXNlY3JldC1rZXk=  # change-me-to-a-random-secret-key
  database-password: Y2hhbmdlLW1lLXRvLWEtc3Ryb25nLXBhc3N3b3Jk    # change-me-to-a-strong-password
  redis-password: Y2hhbmdlLW1lLXRvLWEtcmVkaXMtcGFzc3dvcmQ=         # change-me-to-a-redis-password
  grafana-admin-password: Y2hhbmdlLW1lLXRvLWEtZ3JhZmFuYS1wYXNzd29yZA== # change-me-to-a-grafana-password
  postgres-user: cGVyZmVjdDIxX3VzZXI=                             # perfect21_user
  postgres-db: cGVyZmVjdDIx                                         # perfect21

---
apiVersion: v1
kind: Secret
metadata:
  name: perfect21-tls
  namespace: perfect21
  labels:
    app.kubernetes.io/name: perfect21
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # Replace with actual TLS certificate and key
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t    # Base64 encoded private key

---
apiVersion: v1
kind: Secret
metadata:
  name: perfect21-registry
  namespace: perfect21
  labels:
    app.kubernetes.io/name: perfect21
    app.kubernetes.io/component: registry
type: kubernetes.io/dockerconfigjson
data:
  # Base64 encoded Docker registry credentials
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==