#!/bin/bash
# Auto-mode detection
if [[ "$CE_AUTO_MODE" == "true" ]]; then
    export CE_SILENT_MODE=true
fi
# System Prompt Hook: agent_orchestration_validator
# Auto-generated by Claude Enhancer 5.0 Auto-Trigger System

PROJECT_ROOT="/home/xx/dev/Claude Enhancer 5.0"

# Agent Orchestration Validator
# Ensures proper Agent usage in Phase 3 (Implementation)

if [[ "$CURRENT_PHASE" == "3" ]]; then
    echo "🤖 Phase 3: Implementation - Agent Orchestration Required"
    echo ""
    echo "MANDATORY: Use 4-6-8 Agent Strategy:"
    echo "  - Simple tasks: 4 Agents (5-10 minutes)"
    echo "  - Standard tasks: 6 Agents (15-20 minutes)"
    echo "  - Complex tasks: 8 Agents (25-30 minutes)"
    echo ""
    echo "⚡ Execute ALL Agents in parallel within single function_calls block"
    echo "❌ NEVER call Agents sequentially"
    echo "❌ SubAgents CANNOT call other SubAgents"
    echo ""
    echo "Available Agent Categories:"
    echo "  - Backend: backend-architect, api-designer, database-specialist"
    echo "  - Security: security-auditor, authentication-expert"
    echo "  - Testing: test-engineer, performance-engineer"
    echo "  - Infrastructure: devops-engineer, deployment-specialist"
fi

