# Perfect21 Git工作流配置文件
# 个人编程助手专用配置

version: "1.0.0"

# Git Hooks配置
hooks:
  # 启用的Hook类型
  enabled:
    - pre-commit
    - commit-msg
    - pre-push
    - post-checkout

  # Hook执行配置
  execution:
    parallel: true
    timeout: 300  # 秒
    retry_attempts: 2

  # 各Hook的Agent配置
  agents:
    pre-commit:
      - code-reviewer
      - security-auditor
      - test-engineer
    commit-msg:
      - orchestrator
    pre-push:
      - test-engineer
      - security-auditor
      - devops-engineer
    post-checkout:
      - devops-engineer

# 工作流配置
workflows:
  # 功能开发工作流
  feature:
    branch_pattern: "feature/*"
    merge_strategy: "no-ff"
    require_pr: true
    quality_gates:
      - pre-commit
      - test
      - security-scan
    auto_delete_branch: true

  # Bug修复工作流
  bugfix:
    branch_pattern: "bugfix/*"
    merge_strategy: "squash"
    require_pr: true
    quality_gates:
      - pre-commit
      - test

  # 热修复工作流
  hotfix:
    branch_pattern: "hotfix/*"
    merge_strategy: "fast-forward"
    require_pr: false
    quality_gates:
      - test
      - security-scan

# 分支管理
branches:
  # 受保护的分支
  protected:
    - main
    - master
    - develop
    - "release/*"

  # 自动清理配置
  auto_cleanup:
    enabled: true
    max_age_days: 30
    require_merged: true
    exclude_patterns:
      - "feature/important-*"
      - "hotfix/*"

# 智能提交
smart_commits:
  enabled: true
  # 提交类型检测关键词
  type_keywords:
    feat: ["add", "new", "create", "implement", "introduce"]
    fix: ["fix", "resolve", "correct", "repair", "solve"]
    docs: ["doc", "readme", "comment", "documentation"]
    style: ["format", "style", "lint", "whitespace"]
    refactor: ["refactor", "restructure", "reorganize", "clean"]
    test: ["test", "spec", "coverage", "unit", "integration"]
    chore: ["update", "bump", "maintain", "config", "build"]

  # 作用域检测
  scope_patterns:
    api: ["api", "endpoint", "route", "service"]
    ui: ["ui", "component", "view", "template", "style"]
    db: ["database", "model", "schema", "migration"]
    auth: ["auth", "login", "permission", "security"]
    config: ["config", "setting", "env", "parameter"]

# 个人生产力配置
productivity:
  # 会话跟踪
  session_tracking:
    enabled: true
    auto_save_interval: 5  # 分钟
    productivity_metrics: true

  # 工作时间分析
  working_hours:
    analyze_patterns: true
    suggest_breaks: true
    optimal_session_length: 45  # 分钟

  # 目标设置
  goals:
    daily_commits: 3
    weekly_hours: 20
    quality_score_target: 85

# 通知和报告
notifications:
  # 启用通知类型
  enabled:
    - task_completed
    - pr_ready
    - build_failed
    - quality_gate_failed

  # 报告生成
  reports:
    auto_generate: true
    frequency: "weekly"
    include:
      - productivity_summary
      - code_quality_metrics
      - goal_progress

# 集成配置
integrations:
  # GitHub集成
  github:
    enabled: false
    token: ""  # 需要设置环境变量 GITHUB_TOKEN
    auto_create_pr: false

  # GitLab集成
  gitlab:
    enabled: false
    token: ""  # 需要设置环境变量 GITLAB_TOKEN
    auto_create_mr: false

  # 其他工具集成
  tools:
    vscode: true
    ide_plugins: true
    shell_completion: true

# 高级功能
advanced:
  # AI辅助功能
  ai_assistance:
    smart_suggestions: true
    code_review_insights: true
    commit_message_generation: true

  # 性能优化
  performance:
    cache_git_operations: true
    parallel_agent_execution: true
    async_hook_execution: true

  # 实验性功能
  experimental:
    predictive_conflict_detection: false
    auto_code_formatting: false
    intelligent_branch_suggestions: false

# 用户偏好
preferences:
  # 默认设置
  defaults:
    merge_strategy: "no-ff"
    branch_prefix: "feature"
    commit_template: "conventional"

  # UI偏好
  ui:
    color_output: true
    progress_bars: true
    emoji_indicators: true
    compact_mode: false

  # 语言设置
  locale:
    language: "zh_CN"
    date_format: "%Y-%m-%d"
    time_format: "%H:%M:%S"

# 安全配置
security:
  # 敏感信息检测
  secret_scanning:
    enabled: true
    patterns:
      - "password"
      - "api_key"
      - "secret"
      - "token"

  # 签名验证
  signature_verification:
    require_signed_commits: false
    verify_signatures: false

  # 访问控制
  access_control:
    require_2fa: false
    session_timeout: 3600  # 秒