# Perfect21安全权限配置
# 基于RBAC(Role-Based Access Control)的权限管理

# 角色定义
roles:
  guest:
    description: "未认证用户"
    inherits: []
    permissions: []

  user:
    description: "普通用户"
    inherits: ["guest"]
    permissions:
      - "auth:profile:read"
      - "auth:profile:update"
      - "auth:password:change" 
      - "api:basic:access"

  admin:
    description: "管理员"
    inherits: ["user"]
    permissions:
      - "auth:users:list"
      - "auth:users:read"
      - "auth:users:update"
      - "auth:users:delete"
      - "api:admin:access"
      - "system:config:read"
      - "system:logs:read"

  super_admin:
    description: "超级管理员"
    inherits: ["admin"]
    permissions:
      - "system:*"
      - "auth:*"
      - "api:*"

# 端点权限映射
endpoints:
  # 公开端点 - 不需要认证
  public:
    - path: "/"
      methods: ["GET"]
      auth_required: false
      
    - path: "/health" 
      methods: ["GET"]
      auth_required: false
      
    - path: "/docs"
      methods: ["GET"]
      auth_required: false
      
    - path: "/redoc"
      methods: ["GET"] 
      auth_required: false
      
    - path: "/openapi.json"
      methods: ["GET"]
      auth_required: false

  # 认证端点
  auth:
    - path: "/api/auth/login"
      methods: ["POST"]
      auth_required: false
      rate_limit:
        max_requests: 5
        window_seconds: 300
        
    - path: "/api/auth/register"
      methods: ["POST"]
      auth_required: false
      rate_limit:
        max_requests: 3
        window_seconds: 3600
        
    - path: "/api/auth/logout"
      methods: ["POST"]
      auth_required: true
      permissions: []
      
    - path: "/api/auth/refresh"
      methods: ["POST"]
      auth_required: true
      permissions: []
      
    - path: "/api/auth/profile"
      methods: ["GET"]
      auth_required: true
      permissions: ["auth:profile:read"]
      
    - path: "/api/auth/profile"
      methods: ["PUT", "PATCH"]
      auth_required: true
      permissions: ["auth:profile:update"]
      
    - path: "/api/auth/password"
      methods: ["PUT"]
      auth_required: true
      permissions: ["auth:password:change"]

  # 用户管理端点
  users:
    - path: "/api/users"
      methods: ["GET"]
      auth_required: true
      permissions: ["auth:users:list"]
      roles: ["admin", "super_admin"]
      
    - path: "/api/users/{user_id}"
      methods: ["GET"]
      auth_required: true
      permissions: ["auth:users:read"]
      roles: ["admin", "super_admin"]
      resource_check: "user_access"
      
    - path: "/api/users/{user_id}"
      methods: ["PUT", "PATCH"]
      auth_required: true
      permissions: ["auth:users:update"]
      roles: ["admin", "super_admin"]
      resource_check: "user_modify"
      
    - path: "/api/users/{user_id}"
      methods: ["DELETE"]
      auth_required: true
      permissions: ["auth:users:delete"]
      roles: ["super_admin"]
      resource_check: "user_delete"

  # 系统管理端点
  system:
    - path: "/api/system/config"
      methods: ["GET"]
      auth_required: true
      permissions: ["system:config:read"]
      roles: ["admin", "super_admin"]
      
    - path: "/api/system/logs"
      methods: ["GET"]
      auth_required: true
      permissions: ["system:logs:read"]
      roles: ["admin", "super_admin"]

# 路径匹配规则
path_matching:
  normalize: true           # 标准化路径
  case_sensitive: false     # 大小写敏感
  trailing_slash: ignore    # 忽略尾部斜杠
  max_path_length: 2048     # 最大路径长度
  
# 安全策略
security_policies:
  # 会话安全
  session:
    max_concurrent_sessions: 3
    session_timeout: 3600
    idle_timeout: 1800
    
  # 令牌安全
  token:
    access_token_lifetime: 3600
    refresh_token_lifetime: 604800
    token_rotation_enabled: true
    
  # 路径安全
  path_security:
    block_path_traversal: true
    block_double_encoding: true
    max_redirects: 3
    
  # IP安全
  ip_security:
    enabled: true
    whitelist: []
    blacklist: []
    geo_blocking: false

# 审计配置
audit:
  enabled: true
  log_access_granted: true
  log_access_denied: true
  log_permission_changes: true
  log_role_changes: true
  retention_days: 90
