"""
Type stubs for GitPython
"""

from typing import Any, List, Optional, Union
from pathlib import Path

class Repo:
    def __init__(self, path: Union[str, Path] = ...) -> None: ...
    @property
    def git_dir(self) -> str: ...
    @property
    def working_dir(self) -> str: ...
    @property
    def heads(self) -> List[Any]: ...
    @property
    def active_branch(self) -> Any: ...
    def git(self) -> Any: ...
    def is_dirty(self, **kwargs: Any) -> bool: ...

class Git:
    def __call__(self, *args: Any, **kwargs: Any) -> str: ...
    def status(self, *args: Any) -> str: ...
    def add(self, *args: Any) -> str: ...
    def commit(self, *args: Any) -> str: ...
    def push(self, *args: Any) -> str: ...
    def pull(self, *args: Any) -> str: ...

def is_git_repo(path: Union[str, Path]) -> bool: ...