# Perfect21双发动机系统配置
# Perfect21 (前端) + claude-code-unified-agents (内核) + Claude/Codex (双发动机)
# 版本: 1.0.0 - Git工作流集成完成
# 创建时间: 2025-09-06

version: "1.0.0"
system_name: "Perfect21 Dual Engine System"

# 系统组件配置
components:
  frontend:
    name: "Perfect21"
    type: "web_dashboard"
    port: 8081
    features:
      - "drag_drop_tasks"
      - "parallel_swimlanes"
      - "evidence_drawer"
      - "one_click_routing"
    
  kernel:
    name: "claude-code-unified-agents"
    type: "task_orchestrator"
    mode: "resident_process"
    features:
      - "task_lifecycle_management"
      - "intelligent_routing"
      - "evidence_validation"
      - "health_monitoring"
    
  engines:
    claude:
      name: "Claude Code"
      type: "primary_engine"
      model: "claude-opus-4-1"
      strengths:
        - "planning"
        - "complex_refactoring"
        - "integration"
        - "code_review"
      access_mode: "direct_api"
      
    codex:
      name: "GPT-5 Codex"
      type: "secondary_engine"
      model: "gpt-5"
      strengths:
        - "bulk_generation"
        - "unit_tests"
        - "scaffolding"
        - "performance_scoring"
      access_mode: "mcp_bridge"

# 三条黄金路径配置
golden_paths:
  task_success_rate:
    name: "核心任务执行成功率"
    trigger: "daily_at_09_30_and_17_30"
    success_criteria: "24h_success_rate >= 0.95"
    detection_signal: "GET /status && ledger.success_rate >= 0.95"
    failure_threshold: "< 0.90"
    auto_actions:
      on_failure: ["stop_new_tasks", "enable_repair_mode"]
    
  dual_engine_collaboration:
    name: "双发动机协作健康度"  
    trigger: "after_each_task_completion"
    success_criteria: "handoff_success && cross_review_passed"
    detection_signal: "handoff_bundle.complete=true && review.status=passed"
    failure_threshold: "handoff_failure_rate > 0.02"
    auto_actions:
      on_failure: ["switch_to_single_engine", "generate_repair_task"]
      
  self_repair_responsiveness:
    name: "自修复响应时效"
    trigger: "on_task_failure"
    success_criteria: "repair_task_created_within_30min"
    detection_signal: "failure_detected → repair_task.created_at < 30min"
    failure_threshold: "> 45min"
    auto_actions:
      on_failure: ["escalate_to_human", "emergency_rollback"]

# 任务路由规则矩阵
routing_rules:
  # 基础路由策略
  default_assignments:
    small_file_changes:
      executor: "codex"
      reviewer: "claude"
      criteria: "files <= 3 && lines <= 100"
      
    bulk_generation:
      executor: "codex"
      reviewer: "claude"
      criteria: "type in ['test_generation', 'documentation', 'scaffolding']"
      
    complex_refactoring:
      executor: "claude"
      reviewer: "codex"
      criteria: "files > 3 || cross_file_dependencies"
      
    integration_work:
      executor: "claude"
      reviewer: "codex"
      criteria: "type in ['merge_conflicts', 'api_integration', 'pr_preparation']"
      
    interface_design:
      executor: "claude"
      reviewer: "codex"
      criteria: "type in ['data_models', 'api_design', 'architecture']"

  # 强制切换条件
  force_switch_conditions:
    security_sensitive:
      condition: "path_matches_denylist || contains_secrets"
      forced_executor: "claude"
      reason: "security_review_required"
      
    large_changes:
      condition: "files > 10 || lines > 500"
      forced_executor: "claude" 
      reason: "complex_change_requires_deep_analysis"
      
    golden_path_failure:
      condition: "any_golden_path_failed"
      forced_executor: "repair_mode_only"
      reason: "system_stability_priority"
      
    consecutive_failures:
      condition: "same_task_failed_twice"
      forced_executor: "opposite_engine"
      reason: "engine_specialization_mismatch"

# 安全边界和约束
security_constraints:
  allowlist:
    directories:
      - "/home/xx/dev/Perfect21/**"
      - "/home/xx/dev/Perfect21/**"
      - "/tmp/perfect21_workspace/**"
    file_patterns:
      - "*.py"
      - "*.js"
      - "*.ts"
      - "*.yaml"
      - "*.json"
      - "*.md"
      
  denylist:
    directories:
      - "**/node_modules/**"
      - "**/venv/**"
      - "**/build/**"
      - "**/dist/**"
    files:
      - "**/.env*"
      - "**/secrets/**"
      - "**/credentials/**"
      - "**/*.key"
      - "**/*.pem"
      - "**/production.yaml"
      - "**/prod.config.*"
    operations:
      - "rm_rf_commands"
      - "sudo_operations"
      - "network_access_without_approval"
      
  change_thresholds:
    max_files_per_task: 10
    max_lines_per_task: 500
    max_parallel_tasks: 5
    max_retries_per_task: 2
    max_task_duration_minutes: 60

# 健康目标阈值
health_targets:
  primary_metrics:
    golden_path_pass_rate: 0.95        # 95% 三条黄金路径通过率
    task_first_success_rate: 0.90      # 90% 任务首次成功率  
    repair_closure_rate_24h: 0.80      # 80% 24小时修复关闭率
    rollback_rate: 0.05                # < 5% 回滚率
    evidence_completeness_rate: 1.00   # 100% 证据完整率
    
  secondary_metrics:
    avg_task_completion_time_min: 15   # 平均任务完成时间
    cross_review_agreement_rate: 0.85  # 交叉审查一致性
    self_heal_success_rate: 0.75       # 自修复成功率
    user_intervention_rate: 0.10       # < 10% 人工干预率
    
  alert_thresholds:
    critical: 
      golden_path_pass_rate: 0.80      # 低于80%立即告警
      task_first_success_rate: 0.70    # 低于70%立即告警
    warning:
      golden_path_pass_rate: 0.90      # 低于90%发出警告
      task_first_success_rate: 0.85    # 低于85%发出警告

# 守门人交叉审查规则
gatekeeper_rules:
  default_mode: "cross_engine_review"
  
  review_assignments:
    when_claude_executes:
      reviewer: "codex"
      focus_areas: ["performance", "test_coverage", "code_style"]
      
    when_codex_executes:
      reviewer: "claude"
      focus_areas: ["logic_correctness", "security", "maintainability"]
      
  special_conditions:
    critical_path_changes:
      reviewer: "claude"
      additional_checks: ["security_scan", "regression_test"]
      approval_required: true
      
    large_scale_changes:
      reviewer: "dual_review"  # 两个引擎都审查
      consensus_required: true
      escalation_on_disagreement: true
      
    production_impact:
      reviewer: "claude"
      human_approval_required: true
      rollback_plan_mandatory: true
      
  review_gates:
    mandatory_checks:
      - "evidence_completeness"
      - "test_coverage_adequate"
      - "security_baseline_passed"
      - "no_denylist_violations"
    
    blocking_conditions:
      - "missing_handoff_bundle"
      - "test_failures"
      - "security_vulnerabilities"
      - "golden_path_regression"

# 数据契约规范
data_contracts:
  task_spec:
    required_fields:
      - "task_id"
      - "description"
      - "target_outcome"
      - "acceptance_criteria"
      - "constraints"
      - "estimated_complexity"
    schema_version: "1.0"
    
  handoff_bundle:
    required_fields:
      - "source_engine"
      - "target_engine"
      - "change_summary"
      - "impact_analysis"
      - "pending_tasks"
      - "recommended_next_steps"
    schema_version: "1.0"
    
  evidence_package:
    required_components:
      - "execution_log"
      - "test_results"
      - "code_diff"
      - "golden_path_validation"
    completeness_threshold: 1.0  # 100%必须完整

# 任务建议算法配置
task_suggestion:
  daily_recommendations: 10
  
  prioritization_factors:
    health_score_impact: 0.30      # 对健康分影响权重
    risk_level: 0.25               # 风险等级权重
    urgency: 0.20                  # 时效性权重
    learning_value: 0.15           # 学习价值权重
    resource_efficiency: 0.10      # 资源效率权重
    
  task_categories:
    maintenance:
      weight: 0.30
      examples: ["dependency_updates", "code_cleanup", "documentation"]
      
    feature_development:
      weight: 0.40
      examples: ["new_features", "enhancements", "integrations"]
      
    bug_fixes:
      weight: 0.20
      examples: ["critical_fixes", "regression_fixes", "optimization"]
      
    infrastructure:
      weight: 0.10
      examples: ["monitoring", "deployment", "security"]

# 监控和告警配置
monitoring:
  heartbeat_interval_seconds: 30
  health_check_interval_minutes: 5
  report_generation_times: ["09:30", "17:30", "21:00"]
  
  alert_channels:
    dashboard: true
    log_files: true
    notion_integration: true
    
  log_retention:
    debug_logs_days: 7
    info_logs_days: 30
    error_logs_days: 90

# 自愈和回滚策略
auto_healing:
  enable_self_repair: true
  max_repair_attempts: 2
  repair_timeout_minutes: 30
  
  rollback_triggers:
    golden_path_failure: true
    critical_regression: true
    security_vulnerability: true
    
  rollback_strategy:
    automatic_rollback_window_hours: 24
    require_human_approval_after_hours: 48
    
# 学习和优化配置
continuous_learning:
  enable_pattern_learning: true
  success_pattern_reinforcement: true
  failure_pattern_avoidance: true
  
  learning_card_generation:
    min_daily_cards: 1
    max_daily_cards: 5
    pattern_threshold: 3  # 3次相同模式后生成学习卡
    
# 前端界面配置
frontend_config:
  dashboard_refresh_seconds: 15
  task_drag_drop: true
  real_time_updates: true
  
  swimlane_display:
    show_claude_lane: true
    show_codex_lane: true
    show_queue_depth: true
    show_estimated_completion: true
    
  evidence_drawer:
    auto_open_on_completion: true
    show_execution_timeline: true
    enable_evidence_export: true

# 系统集成配置
integration:
  claude_code:
    api_endpoint: "direct"
    max_concurrent_sessions: 3
    timeout_minutes: 10
    
  codex_bridge:
    mcp_bridge_path: "modules/mcp/codex_mcp_bridge.py"
    max_parallel_requests: 5
    request_timeout_seconds: 60
    
  notion_sync:
    enable_dashboard_sync: true
    sync_interval_hours: 4
    
  git_integration:
    auto_commit_small_changes: false  # 保守策略，需要人工确认
    require_review_for_commits: true
    branch_strategy: "feature_branches"

# 运行时配置
runtime:
  startup_checks:
    - "verify_claude_access"
    - "verify_codex_bridge"
    - "validate_config_syntax"
    - "check_file_permissions"
    - "test_golden_paths"
    
  shutdown_procedures:
    - "complete_running_tasks"
    - "save_state_snapshot"
    - "generate_session_report"
    
  emergency_procedures:
    stop_all_engines: "immediate"
    rollback_last_change: "within_5min"
    human_escalation: "critical_only"

# 版本和兼容性
compatibility:
  min_claude_code_version: "2.0"
  min_python_version: "3.8"
  required_dependencies:
    - "pyyaml"
    - "requests"
    - "psutil"
    
# 配置文件元数据
metadata:
  created_by: "Perfect21 Enhanced V2"
  config_schema_version: "1.0"
  last_validated: "2025-09-06"
  checksum: "auto_generated"