version: 2.12.0
system:
  edition: enhanced-v2-max
  environment: production
  debug: false
  optimization_level: maximum
  intelligence_mode: enhanced
flags:
  strict: true
  cost_optimization: true
  fast_mode: false
  skip_validation: false
  auto_fallback: true
workflow:
  sequence:
  - spec-planner
  - spec-architect
  - developer-primary
  - developer-parallel
  - test-generator
  - test-runner
  - code-reviewer
  - security-auditor
  - performance-analyzer
  - cross-validator
  - quality-gatekeeper
  - coach-qa
  - commit-bot
  execution:
    parallel_execution: true
    force_parallel: true
    skip_optional: false
    parallel_groups:
    - - developer-primary
      - developer-parallel
    - - test-generator
      - test-runner
    - - code-reviewer
      - security-auditor
      - performance-analyzer
    - - cross-validator
      - quality-gatekeeper
    mandatory_agents:
    - spec-planner
    - spec-architect
    - developer-primary
    - test-runner
    - code-reviewer
    - security-auditor
    - cross-validator
    - quality-gatekeeper
    - coach-qa
  quality_gates:
    require_self_eval: true
    evidence_files_required:
    - tests.json
    - review.md
    minimum_test_coverage: 80
    zero_must_fix_tolerance: true
  fix_cycle:
    max_iterations: 3
    auto_retry_on_must_fix: true
    retry_sequence:
    - test-runner
    - code-reviewer
    abort_on_no_progress: true
subagents:
  spec-planner:
    provider: anthropic
    model: claude-opus-4-1-20250805
    parameters:
      thinking:
        type: enabled
        budget_tokens: 8192
    constraints:
      max_input_tokens: 200000
      reasoning_quality: maximum
    fallbacks:
    - claude-opus-4-1-20250805
    - claude-opus-4-20250514
    - claude-sonnet-4-20250514
    mcp_integration:
      enable_collaboration: true
      force_collaboration: true
      task_types:
      - architecture_design
      - complex_reasoning
      - system_design
      - planning
      token_threshold: 50000
      collaboration_models:
      - gpt-5
      collaboration_ratio: 0.5
  spec-architect:
    provider: anthropic
    model: claude-opus-4-1-20250805
    parameters:
      thinking:
        type: enabled
        budget_tokens: 12288
    constraints:
      max_input_tokens: 300000
      reasoning_quality: maximum
      specialization: deep_architecture
    mcp_integration:
      enable_collaboration: true
      task_types:
      - architecture_design
      - system_design
      - scalability_analysis
      collaboration_models:
      - claude-opus-4-1-20250805
  security-auditor:
    provider: anthropic
    model: claude-opus-4-1-20250805
    parameters:
      thinking:
        type: enabled
        budget_tokens: 8192
    constraints:
      max_input_tokens: 200000
      specialization: security_analysis
      mandatory: true
    mcp_integration:
      enable_collaboration: true
      consensus_required: true
      task_types:
      - security_analysis
      - vulnerability_assessment
      - threat_modeling
      collaboration_models:
      - claude-opus-4-1-20250805
  developer-coder:
    provider: openai
    model: gpt-5
    parameters:
      reasoning_effort: high
      verbosity: high
    constraints:
      max_input_tokens: 320000
      self_consistency_passes: 2
    fallbacks:
    - claude-sonnet-4-20250514
    - claude-3-opus
    mcp_integration:
      enable_collaboration: true
      force_collaboration: true
      task_types:
      - code_generation
      - algorithm_optimization
      - refactoring
      - implementation
      token_threshold: 30000
      collaboration_models:
      - claude-opus-4-1-20250805
      collaboration_ratio: 0.5
  developer-primary:
    provider: anthropic
    model: claude-opus-4-1-20250805
    parameters:
      reasoning_effort: high
      verbosity: high
      specialization: primary_implementation
      use_claude_code: true
      sandbox_mode: workspace-write
    constraints:
      max_input_tokens: 320000
      parallel_execution: true
    mcp_integration:
      enable_collaboration: false
      use_claude_code_bridge: true
      task_types:
      - primary_development
      - main_implementation
      - code_generation
      collaboration_models:
      - claude-opus-4-1-20250805
  developer-parallel:
    provider: anthropic
    model: claude-opus-4-1-20250805
    parameters:
      reasoning_effort: high
      verbosity: medium
      specialization: alternative_implementation
      use_claude_code: true
      sandbox_mode: workspace-write
    constraints:
      max_input_tokens: 320000
      parallel_execution: true
    mcp_integration:
      enable_collaboration: true
      use_claude_code_bridge: true
      task_types:
      - alternative_implementation
      - parallel_development
      - code_generation
      collaboration_models:
      - claude-opus-4-1-20250805
  test-generator:
    provider: anthropic
    model: claude-sonnet-4-20250514
    parameters:
      reasoning_effort: high
      verbosity: high
      specialization: comprehensive_testing
      use_claude_code: true
      sandbox_mode: read-only
    constraints:
      max_input_tokens: 260000
      parallel_execution: true
    mcp_integration:
      enable_collaboration: false
      use_claude_code_bridge: true
      task_types:
      - test_generation
      - test_coverage
      - edge_case_testing
      collaboration_models:
      - claude-sonnet-4-20250514
  test-runner:
    provider: openai
    model: gpt-5-mini
    parameters:
      reasoning_effort: medium
      verbosity: medium
    constraints:
      max_input_tokens: 260000
      test_types:
      - unit
      - integration
      - edge_cases
      - performance
    mcp_integration:
      enable_collaboration: true
      primary_models:
      - claude-sonnet-4-20250514
      - claude-opus-4-1-20250805-mini
      quality_models:
      - claude-3-sonnet
      - claude-sonnet-4-20250514
      token_optimization: true
      cost_priority: balanced
      collaboration_models:
      - claude-sonnet-4-20250514
  code-reviewer:
    provider: anthropic
    model: claude-opus-4-1-20250805
    parameters:
      thinking:
        type: enabled
        budget_tokens: 8192
    constraints:
      max_input_tokens: 200000
      review_policy: deep
      security_focus: true
      performance_analysis: true
    fallbacks:
    - claude-opus-4-20250514
    - claude-sonnet-4-20250514
    mcp_integration:
      enable_collaboration: true
      task_types:
      - security_analysis
      - code_review
      - architecture_review
      consensus_required: true
      collaboration_models:
      - gpt-5
  coach-qa:
    provider: anthropic
    model: claude-opus-4-1-20250805
    parameters:
      thinking:
        type: enabled
        budget_tokens: 8192
    constraints:
      max_input_tokens: 200000
      mandatory: true
      audit_checklist:
      - authentication
      - authorization
      - payment_security
      - pii_handling
      - secrets_exposure
      - concurrency_safety
      - injection_prevention
    fallbacks:
    - claude-opus-4-20250514
    - claude-sonnet-4-20250514
  commit-bot:
    provider: openai
    model: gpt-5
    parameters:
      verbosity: medium
      style: conventional_commits
    constraints:
      max_input_tokens: 100000
    mcp_integration:
      enable_collaboration: false
      primary_models:
      - claude-haiku-3-5-20241022
      - claude-3-haiku
      quality_threshold: basic
  cross-validator:
    provider: anthropic
    model: claude-opus-4-1-20250805
    parameters:
      thinking:
        type: enabled
        budget_tokens: 8192
      specialization: cross_model_validation
    constraints:
      max_input_tokens: 400000
      parallel_execution: true
      mandatory: true
    mcp_integration:
      enable_collaboration: true
      consensus_required: true
      task_types:
      - cross_validation
      - quality_comparison
      - implementation_analysis
      collaboration_models:
      - claude-opus-4-1-20250805
  quality-gatekeeper:
    provider: anthropic
    model: claude-opus-4-1-20250805
    parameters:
      thinking:
        type: enabled
        budget_tokens: 12288
      specialization: final_quality_control
    constraints:
      max_input_tokens: 500000
      mandatory: true
    mcp_integration:
      enable_collaboration: true
      consensus_required: true
      task_types:
      - final_review
      - quality_gates
      - release_readiness
      collaboration_models:
      - claude-opus-4-1-20250805
  performance-analyzer:
    provider: anthropic
    model: claude-opus-4-1-20250805
    parameters:
      thinking:
        type: enabled
        budget_tokens: 8192
      specialization: performance_optimization
    constraints:
      max_input_tokens: 300000
      parallel_execution: true
    mcp_integration:
      enable_collaboration: true
      task_types:
      - performance_analysis
      - optimization_suggestions
      - scalability_review
      collaboration_models:
      - claude-opus-4-1-20250805
mcp_system:
  enabled: true
  coordinator_endpoint: http://localhost:8000/mcp
  codex_cli:
    enabled: true
    bridge_path: /home/xx/dev/Vibepilot_Kit/modules/mcp/claude_code_bridge.py
    default_model: claude-opus-4-1-20250805
    default_sandbox: read-only
    timeout: 300
    authentication: chatgpt_pro_login
    priority_limits:
      high_priority: 2
      medium_priority: 4
      low_priority: 6
    circuit_breaker:
      failure_threshold: 5
      recovery_timeout_minutes: 5
      halfopen_max_calls: 2
    retry_strategy:
      max_retries: 2
      initial_delay_seconds: 30
      exponential_backoff: true
  chatgpt_pro:
    enabled: true
    api_key: ${CHATGPT_PRO_API_KEY}
    base_url: https://api.openai.com/v1
    subscription_tier: pro
    unlimited_requests: true
    priority_access: true
    models:
    - gpt-5
    - gpt-5-mini
    - gpt-4-turbo
    - gpt-4
  token_optimization:
    enabled: true
    strategies:
      cost_saving:
        threshold_savings: 0.3
        max_quality_loss: 0.1
      load_balancing:
        distribute_requests: true
        avoid_rate_limits: true
      intelligent_routing:
        task_complexity_analysis: true
        model_capability_matching: true
  collaboration_modes:
    consensus:
      min_models: 2
      agreement_threshold: 0.8
      applicable_tasks:
      - security_analysis
      - architecture_review
    parallel:
      max_models: 3
      merge_strategy: best_of_n
      applicable_tasks:
      - testing
      - optimization
    sequential:
      pipeline_stages:
      - design
      - implement
      - review
      - test
      handoff_validation: true
slo_guards:
  max_tool_calls_per_agent: 10
  max_reflect_rounds: 2
  max_tokens_per_stage: 200000
  timeout_minutes: 45
  agent_timeouts:
    spec-planner: 180
    spec-architect: 240
    developer-primary: 300
    developer-parallel: 300
    test-generator: 180
    test-runner: 120
    code-reviewer: 180
    security-auditor: 240
    performance-analyzer: 180
    cross-validator: 120
    quality-gatekeeper: 180
    coach-qa: 120
    commit-bot: 60
observability:
  emit_headers:
  - X-Resolved-Model
  - X-Context-Used
  - X-Reasoning-Effort
  - X-Cost
  - X-Quality-Level
  retention_days: 30
  detailed_logging: true
  performance_tracking: true
model_resolver:
  architect:
    current: opus
    provider: anthropic
    channel: stable
  coder:
    current: claude-opus-4-1-20250805
    provider: anthropic
    channel: stable
  tester_fast:
    current: claude-sonnet-4-20250514
    provider: anthropic
    channel: stable
  reviewer:
    current: opus
    provider: anthropic
    channel: stable
  writer_efficient:
    current: claude-sonnet-4-20250514
    provider: anthropic
    channel: stable
  security_architect:
    current: opus
    provider: anthropic
    channel: stable
security:
  strict_mode: true
  protected_paths:
  - .env
  - keys/
  - deploy/
  - .git/
  - config/
  - .claude/
  denied_commands:
  - rm -rf
  - sudo
  - chmod 777
  - '>/dev/null 2>&1'
  audit_all_changes: true
performance:
  priority: quality_first
  track_costs: true
  alert_on_excessive_usage: true
evaluation:
  standards: maximum
  weights:
    tests: 0.35
    review: 0.35
    security: 0.3
  thresholds:
    pass_score: 90
    must_fix_limit: 0
    should_fix_limit: 3
    test_coverage_min: 80
logging:
  level: INFO
  detailed_agent_logs: true
  performance_metrics: true
  quality_metrics: true
  cost_tracking: true
compatibility:
  legacy_support: false
  migration_assistance: true
slo_thresholds:
  golden_path_success_rate: 0.99
  golden_path_timeout_seconds: 300
  chronicle_p95_latency: 120
  chronicle_event_drop_rate: 0.01
  quality_gate_pass_rate: 0.85
  test_coverage_min: 80
  activation_gate_usage_min: 5
  activation_gate_freeze_days: 7
  activation_gate_sunset_days: 14
  error_budget_window_days: 30
  error_budget_max_failures: 7
  daily_max_feature_pr: 2
  max_change_files_per_pr: 3
  max_change_lines_per_pr: 200
kernel_health:
  l0_heartbeat_interval_minutes: 15
  l0_heartbeat_timeout_seconds: 30
  l0_critical_processes:
  - vibepilot-enhanced-v2
  - python3.*chronicle.*
  l0_critical_files:
  - /home/xx/dev/Vibepilot_Kit/eval/logs
  - /home/xx/dev/Vibepilot_Kit/eval/workflow_state
  l1_golden_path_cron: 0 * * * *
  l1_soft_timeout_minutes: 8
  l1_hard_timeout_minutes: 15
  l2_reality_check_cron: 50 23 * * *
  l2_usage_analysis_days: 7
  l2_max_pending_decisions: 5
sentinel_config:
  enabled: true
  trigger_conditions:
    consecutive_failures: 2
    no_events_minutes: 30
    high_error_rate: 0.5
  permissions:
    can_create_branch: true
    can_open_pr: true
    can_push_to_main: false
    can_modify_config: false
  actions:
    enable_safe_mode: true
    cleanup_locks: true
    reset_queues: true
