# Claude Enhancer Configuration
# Version: 6.2.0

version: "6.2.0"

# Workflow Configuration
workflow:
  phases: 8  # P0-P7
  auto_mode: false
  quality_gates: true

# Agent Strategy
agents:
  min_agents: 3
  recommended: 6
  max_parallel: 8

# Quality Settings
quality:
  pre_commit_checks: true
  syntax_validation: true
  security_scan: true
  performance_monitoring: true

# Git Configuration
git:
  protected_branches:
    - main
    - master
    - production
  auto_branch: false
  commit_conventions: true

# Performance Thresholds
performance:
  pre_commit_max_ms: 500
  pre_push_max_ms: 1000
  test_suite_max_sec: 30

# Testing Configuration
testing:
  unit_tests: true
  integration_tests: true
  bdd_tests: true
  coverage_threshold: 80

# Documentation
documentation:
  max_root_docs: 7
  auto_cleanup: true
  archive_old: true
