version: "6.2.0"
enforcement:
  enabled: true
  mode: "strict"

  task_namespace:
    enabled: true
    path: ".gates"
    index_file: "_index.json"
    max_tasks: 50
    cleanup_days: 90

  agent_evidence:
    enabled: true
    min_agents:
      full_lane: 3
      fast_lane: 0
    required_agents:
      P3: [backend-architect, test-engineer]
      P4: [test-engineer, security-auditor]
      P5: [code-reviewer]

  fast_lane:
    enabled: true
    max_consecutive: 5
    require_full_every: 10

  hooks:
    pre_commit:
      enabled: true
      timeout: 30
    pre_push:
      enabled: true
      timeout: 60

  bypass_detection:
    enabled: true
    block_flags: ["--no-verify", "--force"]
    alert_on_attempt: true

performance:
  hook_execution:
    fast_lane_max_ms: 500
    full_lane_max_ms: 30000

monitoring:
  enabled: true
  metrics_file: ".workflow/_reports/enforcement_metrics.json"
