# Perfect21 快速开发工作流模板
name: 快速开发工作流
version: 3.0
philosophy: "快速迭代，持续改进"
target_quality: development_grade
estimated_time: "30-60分钟"

metadata:
  description: "适用于简单任务的快速开发工作流"
  suitable_for: ["Bug修复", "小功能", "配置更改", "文档更新", "测试编写"]
  required_agents: ["根据任务动态选择1-3个agents"]

# ===== Claude Code执行策略 =====
execution_strategy:
  mode: "fast_track"
  parallel_when_beneficial: true
  skip_optional_stages: true

stages:
  # ===== 阶段1：快速分析 =====
  - name: quick_analysis
    description: "快速理解任务并制定方案"
    execution_mode: sequential  # 简单任务顺序执行即可
    thinking_mode: normal
    agents: ["business-analyst"]  # 通常一个agent就够了

    claude_instruction: |
      ## 阶段1：快速分析

      调用最相关的agent分析任务：
      - Bug修复 → @code-reviewer
      - 新功能 → @business-analyst 或 @backend-architect
      - 文档 → @technical-writer
      - 测试 → @test-engineer

      要求：快速明确任务范围和解决方案

  # ===== 阶段2：直接实现 =====
  - name: direct_implementation
    description: "直接实现解决方案"
    execution_mode: sequential
    thinking_mode: normal
    depends_on: ["quick_analysis"]

    claude_instruction: |
      ## 阶段2：直接实现

      根据任务类型执行：
      - 代码修改：直接编辑文件
      - 测试添加：编写测试用例
      - 文档更新：更新相关文档

      要求：专注核心功能，避免过度设计

  # ===== 阶段3：快速验证 =====
  - name: quick_validation
    description: "快速验证结果"
    execution_mode: sequential
    thinking_mode: normal
    depends_on: ["direct_implementation"]

    claude_instruction: |
      ## 阶段3：快速验证

      基础验证：
      1. 运行相关测试
      2. 检查代码规范
      3. 确认功能正常

      要求：确保改动不影响现有功能

# ===== 任务类型配置 =====
task_types:
  bug_fix:
    primary_agent: "code-reviewer"
    validation: "运行测试"
    estimated_time: "15-30分钟"

  small_feature:
    primary_agent: "backend-architect"
    validation: "功能测试"
    estimated_time: "30-60分钟"

  documentation:
    primary_agent: "technical-writer"
    validation: "文档审查"
    estimated_time: "15-30分钟"

  test_writing:
    primary_agent: "test-engineer"
    validation: "测试执行"
    estimated_time: "20-40分钟"

  configuration:
    primary_agent: "devops-engineer"
    validation: "配置检查"
    estimated_time: "10-20分钟"

# ===== 快速决策规则 =====
quick_decisions:
  - condition: "改动少于50行"
    action: "跳过架构设计"

  - condition: "仅修改配置"
    action: "跳过代码审查"

  - condition: "仅添加测试"
    action: "跳过安全审计"

  - condition: "紧急修复"
    action: "最小化验证流程"

# ===== 简化的Hook =====
hooks:
  pre_execution:
    - name: task_scope_check
      description: "确认任务范围适合快速工作流"

  post_execution:
    - name: quick_summary
      description: "生成简要改动总结"