openapi: 3.0.0
info:
  title: Claude Enhancer API
  version: 6.2.0
  description: API contracts for Claude Enhancer workflow system
paths:
  /workflow/start:
    post:
      summary: Start a workflow
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                phase:
                  type: string
      responses:
        '200':
          description: Workflow started
  /agents/select:
    post:
      summary: Select agents for task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                task:
                  type: string
                complexity:
                  type: integer
      responses:
        '200':
          description: Agents selected
