# Claude Code Hook Configuration
# Hook行为配置文件

version: "1.0"
description: "Claude Code多Agent并行执行配置"

# 核心规则
rules:
  # Agent数量限制
  min_agents: 3           # 最少Agent数量
  max_agents: 10          # 最多Agent数量

  # 执行模式
  enforce_parallel: true  # 强制并行执行
  warn_sequential: true   # 警告顺序执行

  # 违规处理
  block_on_violation: true    # 违规时阻止执行
  show_suggestions: true       # 显示改进建议

  # 任务识别
  auto_detect_task: true       # 自动识别任务类型
  suggest_agents: true         # 推荐Agent组合

# 任务类型定义
task_types:
  authentication:
    keywords: ["登录", "认证", "auth", "jwt", "oauth", "用户", "权限"]
    required_agents:
      - backend-architect
      - security-auditor
      - test-engineer
      - api-designer
      - database-specialist
    min_count: 5

  api_development:
    keywords: ["api", "接口", "rest", "graphql", "endpoint"]
    required_agents:
      - api-designer
      - backend-architect
      - test-engineer
      - technical-writer
    min_count: 4

  database_design:
    keywords: ["数据库", "database", "schema", "sql", "mongodb"]
    required_agents:
      - database-specialist
      - backend-architect
      - performance-engineer
    min_count: 3

  frontend_development:
    keywords: ["前端", "frontend", "react", "vue", "ui", "界面"]
    required_agents:
      - frontend-specialist
      - ux-designer
      - test-engineer
    min_count: 3

  testing:
    keywords: ["测试", "test", "jest", "pytest", "e2e"]
    required_agents:
      - test-engineer
      - e2e-test-specialist
      - performance-tester
    min_count: 3

# 日志设置
logging:
  enabled: true
  level: "INFO"
  file: "/tmp/claude-hooks.log"

# 白名单（跳过检查）
whitelist:
  # 某些操作可以跳过
  operations:
    - "rollback"
    - "hotfix"
    - "emergency"

  # 某些路径可以跳过
  paths:
    - "*.md"
    - "*/test/*"
    - "*/docs/*"
