debug:
  dry_run: false
  enabled: false
  timing_reports: true
  verbose_logging: false
default_hook_group: standard
environments:
  development:
    hook_group: standard
    skip_slow_hooks: true
    strict_mode: false
  production:
    hook_group: complete
    skip_slow_hooks: false
    strict_mode: true
  staging:
    hook_group: advanced
    skip_slow_hooks: false
    strict_mode: true
global:
  log_level: INFO
  max_workers: 4
  parallel_execution: true
  project_name: Perfect21
  timeout: 300
  version: 2.1.0
hook_groups:
  advanced:
    description: 高级开发hooks
    hooks:
    - pre-commit
    - commit-msg
    - post-commit
    - prepare-commit-msg
    - pre-push
    - post-checkout
    - post-merge
    - pre-rebase
  complete:
    description: 完整的企业级hooks
    hooks:
    - pre-commit
    - commit-msg
    - post-commit
    - prepare-commit-msg
    - pre-push
    - post-checkout
    - post-merge
    - post-rewrite
    - pre-rebase
    - pre-auto-gc
    - applypatch-msg
    - pre-applypatch
    - post-applypatch
  essential:
    description: 必需的核心hooks
    hooks:
    - pre-commit
    - commit-msg
    - pre-push
  standard:
    description: 标准开发hooks
    hooks:
    - pre-commit
    - commit-msg
    - post-commit
    - pre-push
    - post-checkout
hooks:
  applypatch-msg:
    agent: '@business-analyst'
    category: patch_workflow
    description: 补丁消息验证
    enabled: false
    parallel: false
    plugins:
    - patch_validator
    priority: medium
    timeout: 30
    triggers:
    - patch_validation
    - message_check
  commit-msg:
    agent: '@business-analyst'
    category: commit_workflow
    description: 提交消息格式验证
    enabled: true
    parallel: false
    plugins:
    - message_validator
    priority: high
    rules:
      allowed_types:
      - feat
      - fix
      - docs
      - style
      - refactor
      - test
      - chore
      format: conventional
      max_length: 72
      require_issue_link: false
    timeout: 30
    triggers:
    - message_format
    - issue_linking
    - conventional_commits
  post-applypatch:
    agent: '@test-engineer'
    category: patch_workflow
    description: 应用补丁后测试
    enabled: false
    parallel: true
    plugins:
    - patch_tester
    priority: medium
    timeout: 180
    triggers:
    - patch_testing
    - regression_check
  post-checkout:
    agent: '@devops-engineer'
    category: branch_workflow
    description: 分支切换后环境配置
    enabled: true
    parallel: true
    plugins:
    - environment_manager
    - dependency_checker
    priority: medium
    timeout: 120
    triggers:
    - environment_setup
    - dependency_check
    - config_update
  post-commit:
    agent: '@devops-engineer'
    category: commit_workflow
    description: 提交后通知和统计
    enabled: true
    parallel: true
    plugins:
    - notification_sender
    - metrics_collector
    priority: low
    timeout: 60
    triggers:
    - notifications
    - metrics
    - backup
  post-merge:
    agent: '@test-engineer'
    category: branch_workflow
    description: 合并后集成测试
    enabled: true
    parallel: true
    plugins:
    - integration_tester
    - conflict_resolver
    priority: high
    timeout: 180
    triggers:
    - integration_tests
    - conflict_resolution
    - cleanup
  post-rewrite:
    agent: '@devops-engineer'
    category: branch_workflow
    description: 重写操作后清理
    enabled: false
    parallel: true
    plugins:
    - cleanup_manager
    priority: low
    timeout: 60
    triggers:
    - cleanup
    - backup_update
  pre-applypatch:
    agent: '@code-reviewer'
    category: patch_workflow
    description: 应用补丁前检查
    enabled: false
    parallel: true
    plugins:
    - compatibility_checker
    priority: medium
    timeout: 120
    triggers:
    - compatibility_check
    - code_review
  pre-auto-gc:
    agent: '@devops-engineer'
    category: maintenance
    description: 垃圾回收前备份
    enabled: false
    parallel: false
    plugins:
    - backup_manager
    priority: low
    timeout: 120
    triggers:
    - backup_creation
    - cleanup_verification
  pre-commit:
    agent: auto
    branch_rules:
      feature/*:
        agent: '@code-reviewer'
        required_checks:
        - code_review
        - basic_tests
        strict_mode: false
      hotfix/*:
        agent: '@test-engineer'
        required_checks:
        - critical_tests
        - security_scan
        strict_mode: true
      main:
        agent: '@orchestrator'
        required_checks:
        - code_review
        - security_scan
        - test_suite
        strict_mode: true
    category: commit_workflow
    description: 提交前代码质量检查
    enabled: true
    parallel: true
    plugins:
    - commit_quality
    - security_scan
    priority: critical
    timeout: 120
    triggers:
    - code_quality
    - security_scan
    - linting
    - format_check
  pre-push:
    agent: auto
    branch_rules:
      develop:
        agent: '@test-engineer'
        required_checks:
        - unit_tests
        - integration_tests
      feature/*:
        agent: '@code-reviewer'
        required_checks:
        - basic_tests
        - lint_check
      main:
        agent: '@orchestrator'
        required_checks:
        - full_test_suite
        - security_scan
        - performance_tests
        - integration_tests
    category: push_workflow
    description: 推送前完整验证
    enabled: true
    parallel: true
    plugins:
    - test_runner
    - build_validator
    priority: critical
    timeout: 300
    triggers:
    - test_suite
    - integration_tests
    - build_verification
  pre-rebase:
    agent: '@code-reviewer'
    category: advanced
    description: 变基前冲突预检查
    enabled: false
    parallel: false
    plugins:
    - conflict_detector
    priority: medium
    timeout: 60
    triggers:
    - conflict_detection
    - history_validation
  prepare-commit-msg:
    agent: '@business-analyst'
    category: commit_workflow
    description: 自动生成提交消息模板
    enabled: true
    parallel: false
    plugins:
    - message_template
    priority: medium
    timeout: 30
    triggers:
    - template_generation
    - issue_integration
integrations:
  capability_discovery:
    auto_discover_plugins: true
    enabled: true
    scan_interval: 300
  claude_agents:
    agents_dir: .claude/agents
    base_path: core/claude-code-unified-agents
    enabled: true
  version_manager:
    auto_version_check: true
    enabled: true
    require_version_consistency: true
plugins:
  commit_quality:
    config:
      check_docstrings: true
      check_imports: true
      max_line_length: 88
    enabled: true
    type: built-in
  message_validator:
    config:
      enforce_conventional: true
      max_subject_length: 72
      require_body: false
    enabled: true
    type: built-in
  notification_sender:
    config:
      email_recipients: []
      slack_channel: ''
      webhook_url: ''
    enabled: false
    type: external
  security_scan:
    config:
      check_secrets: true
      scan_dependencies: true
      validate_permissions: true
    enabled: true
    type: built-in
  test_runner:
    config:
      coverage_threshold: 80
      parallel_jobs: 4
      test_command: python -m pytest
    enabled: true
    type: built-in
