openapi: 3.0.0
info:
  title: Claude Enhancer API
  version: 5.3.0
  description: Complete API specification for Claude Enhancer workflow system
servers:
  - url: http://localhost:8000/api/v1
paths:
  /workflow/start:
    post:
      summary: Start a new workflow
      tags: [Workflow]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WorkflowStart'
      responses:
        '200':
          description: Workflow started successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WorkflowResponse'
  /agents/select:
    post:
      summary: Select agents for task
      tags: [Agents]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AgentSelection'
      responses:
        '200':
          description: Agents selected
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'
  /phases/{phase}/transition:
    post:
      summary: Transition between phases
      tags: [Workflow]
      parameters:
        - name: phase
          in: path
          required: true
          schema:
            type: string
            enum: [P0, P1, P2, P3, P4, P5, P6, P7]
      responses:
        '200':
          description: Transition successful
components:
  schemas:
    WorkflowStart:
      type: object
      required: [task, phase]
      properties:
        task:
          type: string
        phase:
          type: string
    WorkflowResponse:
      type: object
      properties:
        id:
          type: string
        status:
          type: string
    AgentSelection:
      type: object
      required: [task, complexity]
      properties:
        task:
          type: string
        complexity:
          type: integer
          minimum: 1
          maximum: 10
    AgentResponse:
      type: object
      properties:
        agents:
          type: array
          items:
            type: string
        count:
          type: integer
