name: Branch-Protection Guard
on:
  schedule:
    - cron: "0 3 * * 1"  # Every Monday at 03:00 UTC
  push:
    paths:
      - ".git/hooks/**"
      - ".workflow/**"
      - "bp_verify.sh"
      - ".github/workflows/**"
      - ".claude/hooks/**"
    branches: ["main"]
  workflow_dispatch:  # Manual trigger

jobs:
  verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup GitHub CLI
        uses: cli/gh-extension-install@v1
        with:
          extension: "gh"

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Setup gh auth
        run: gh auth setup-git
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Branch Protection verification probe
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./bp_verify.sh
          ./bp_verify.sh || {
            echo "::error::Branch Protection verification failed! Check artifacts for evidence."
            exit 1
          }

      - name: Upload probe evidence logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bp-probe-artifacts-${{ github.run_number }}
          path: |
            /tmp/commit.log
            /tmp/push_main.log
            /tmp/push_main_nov.log
            /tmp/merge_attempt.log
          retention-days: 90

      - name: Check for protection degradation
        if: failure()
        run: |
          echo "::warning::⚠️ Branch Protection verification failed!"
          echo "::warning::This indicates one or more protection layers have been compromised."
          echo "::warning::Review the uploaded artifacts and restore protection using scripts/restore_bp.sh"

      - name: Report success
        if: success()
        run: |
          echo "✅ All 3 protection layers verified successfully"
          echo "📊 Evidence logs uploaded to artifacts"
