name: Security-Scan
on: [pull_request, push]
permissions:
  contents: read
  security-events: write
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Secret Scan
        run: |
          if git diff HEAD~1..HEAD | grep -E 'AKIA[0-9A-Z]{16}|BEGIN.*PRIVATE KEY'; then
            echo "::error::Secrets detected!"
            exit 1
          fi
