name: Security Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # Weekly on Monday
  workflow_dispatch:

jobs:
  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Secret Detection
        run: |
          echo "🔍 Scanning for secrets..."
          # Basic secret detection
          if grep -rEi "password|api_key|token|secret" . --exclude-dir=.git --exclude="*.md" 2>/dev/null | grep -E "=.*['\"]"; then
            echo "⚠️ Potential secrets found"
          else
            echo "✅ No obvious secrets detected"
          fi

      - name: Security Report
        run: |
          echo "✅ Security scan completed"
